import timeline from "./data/timeline.json";
import editJson from "./data/edit.json";
import type { Part } from "./ui";

// timeline.json is generated by scripts/build_base.py (never edit by hand)
// edit.json is written by Claude for every video (see references/edit-schema.md)

export const FPS = 30;
export const W = 1080;
export const H = 1920;

export type Seg = { kind: string; n: number | null; s: number; e: number; from_: number; dur: number; label?: string };
export type Word = { text: string; start: number; end: number; seg: number };
export const T = timeline as unknown as { segs: Seg[]; total_video_frames: number; words: Word[] };

export type Card = {
  from: number; to: number; style: "light" | "dark" | "accent"; anim?: "drop" | "flip" | "settle";
  label?: string; num?: number; size?: number; lines: Part[][]; block_at?: number;
};
export type Question = { seg: number; n: number; keyword: string; kw_at: number };
export type Scene = { type: string; from: number; to: number; n?: number; tag?: string; props: Record<string, any> };
export type Behind = { from: number; to: number; lines: Part[][]; size: number; y: number; matte_dir: string };
export type EndCard = {
  dur: number; chips?: [string, boolean][]; label: string; lines: Part[][];
  cta_label: string; keyword: string; sub: string;
};
export type Edit = {
  example_label?: string; // badge on example scenes, default "ESEMPIO" ("" = hide)
  sections_total: number;
  question_label: string; // e.g. "OBIETTIVO {n} DI {total}"
  question_pre: string; // e.g. "VUOI PIÙ"
  questions: Question[];
  cards: Card[];
  punches: number[];
  scenes: Scene[];
  behind: Behind[];
  captions: { keywords: string[]; top: number; hide_in_questions: boolean };
  end: EndCard | null;
  cover: { image: string; scale: number; origin: string; label: string; pills: string[]; lines: Part[][]; sub: string; stickers: { icon: string; big: string; small?: string; x: number; y: number; rot: number; style?: "light" | "dark" | "accent" }[] };
  music: { enabled: boolean; bpm?: number; file?: string | null; gain?: number };
};
export const E = editJson as unknown as Edit;

export const END_FROM = T.total_video_frames;
export const END_DUR = E.end ? E.end.dur : 0;
export const TOTAL = T.total_video_frames + END_DUR;
export const segAt = (f: number) => T.segs.find((s) => f >= s.from_ && f < s.from_ + s.dur);
